version: '3'

services:
  photo_gallery:
    build: photo_gallery_server/
    depends_on:
      - 'database'
    ports:
      - '3003:3003'

  product_details:
    build: product_details_server/
    depends_on:
      - 'database'
      ports:
        - '3002:3002'

  database:
    image: mongo:latest